stages:
  - build
  - deploy

variables:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: gmna-deployment
  ECR_IMAGE_TAG: coop
  KUBE_CONFIG_PATH: $KUBECONFIG
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache aws-cli curl
    - aws configure set region $AWS_REGION
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  script:
    - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$ECR_IMAGE_TAG .
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$ECR_IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  image: 
    name: amazon/aws-cli:latest
  before_script:
    - amazon-linux-extras install kubectl
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
  script:
    - kubectl apply -f deployment.yaml
  only:
    - main