FROM openjdk:17-jdk-slim

# 작업 디렉토리 설정
WORKDIR /app

# 빌드 인수 정의 (기본값 제거 - 빌드 시 주입)
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_DATASOURCE_DRIVER_CLASS_NAME
ARG SERVER_PORT

# 환경변수 설정 (ARG에서 값을 가져옴)
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
ENV SERVER_PORT=${SERVER_PORT}

# JAR 파일 복사
COPY backend/build/libs/*.jar app.jar

# 포트 노출
EXPOSE ${SERVER_PORT}

# 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "/app/app.jar"]